### ISSUE TITLE
Changes needed for final deployment

### ISSUE THREAD

**Issue by brohithkr** [TechForAutismDyslexia/imagematching#1]
### In order to deploy the game on the final website, the following changes are needed.
Make the changes in a new draft PR titled `Final deployment prep` to this repo and add `Fixes #1` as its description.

## Changes requested.
- [ ] Remove unnecessary folders like `preview` folder and json files not needed by game. 
- [ ] Remove `js` files from `Public` folder.
- [ ] Use custom icon for your game instead of default react icon.
- [ ] Give a custom title to your game.

**Comment by Jai-JAP** [comment]
From now you cannot push directly to the `main` branch, To make changes submit a PR.
